import {cp,mkdir,readFile,readdir,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
const destination=path.resolve(process.argv[2] || 'output/aliyun-swas-manage/scene-effects-20261003');
const stage=path.join(destination,'stage');
const target=path.join(stage,'steam');
await mkdir(destination,{recursive:true});
await cp('dist',target,{recursive:true,errorOnExist:true,force:false});
for(const file of ['LICENSE','THIRD_PARTY_NOTICES.md','content-sources.md','ASSETS.md']) await cp(file,path.join(target,file));
const indexPath=path.join(target,'index.html');
let html=await readFile(indexPath,'utf8');
if(!html.includes('/steam/assets/'))throw new Error('Build with VITE_BASE_PATH=/steam/ before packaging.');
if(html.includes('class="aidazi-shell"'))throw new Error('Host shell already present.');
html=html.replace('</head>','<link rel="canonical" href="https://aidazi.tech/steam/"><link rel="stylesheet" href="/steam/aidazi-shell.css?v=3"></head>');
html=html.replace(/(<body[^>]*>)/i,'$1<div class="aidazi-shell"><div class="aidazi-shell-inner"><a href="/" aria-label="返回 AI 搭子首页"><span aria-hidden="true">←</span> AI 搭子</a><span class="aidazi-shell-divider" aria-hidden="true">/</span><span>学习小岛</span><span class="aidazi-shell-note">陪小小的好奇心，一起长大</span></div></div>');
await writeFile(indexPath,html);
await writeFile(path.join(target,'aidazi-shell.css'),'.aidazi-shell{background:#10202a;border-bottom:1px solid #354c58;color:#9db5c2;font:11px/1.4 "Avenir Next","PingFang SC",sans-serif}.aidazi-shell-inner{min-height:44px;max-width:1280px;margin:auto;padding:0 32px;display:flex;gap:13px;align-items:center}.aidazi-shell a{align-self:stretch;display:flex;gap:8px;align-items:center;color:#d9c3a3;text-decoration:none;font-weight:650;min-height:44px}.aidazi-shell a:hover{color:#e8d6bd}.aidazi-shell a:focus-visible{outline:2px solid #d8be97;outline-offset:3px}.aidazi-shell-divider{color:#5e7886}.aidazi-shell-note{margin-left:auto;font-size:10px;color:#819cab}@media(max-width:680px){.aidazi-shell-inner{padding-inline:22px;gap:10px}.aidazi-shell-note{display:none}}\n');
const escape=text=>text.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const license=await readFile('LICENSE','utf8'),notices=await readFile('THIRD_PARTY_NOTICES.md','utf8');
await writeFile(path.join(target,'attribution.html'),`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>小小发现家 · 项目与第三方说明</title><style>body{margin:0;background:#10202a;color:#c8dbe5;font:16px/1.8 system-ui,sans-serif}main{max-width:850px;margin:auto;padding:40px 24px}a{color:#d8be97}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:inherit}</style></head><body><main><a href="/steam/">返回小小发现家</a> · <a href="/">返回 AI 搭子</a><h1>项目与第三方说明</h1><p><a href="https://github.com/chataiwalking/steam-discovery">项目源代码</a> · <a href="/steam/content-sources.md">课程知识来源</a></p><h2>第三方组件与素材</h2><pre>${escape(notices)}</pre><h2>MIT License</h2><pre>${escape(license)}</pre></main></body></html>`);
const revision=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim();
const lessons=JSON.parse(await readFile('src/content/lessons.json','utf8'));
await writeFile(path.join(target,'release.json'),JSON.stringify({revision,builtAt:new Date().toISOString(),lessons:lessons.length,tracks:150,narrations:450},null,2)+'\n');
const files=[];
async function walk(directory){for(const item of await readdir(directory,{withFileTypes:true})){const file=path.join(directory,item.name);if(item.isDirectory())await walk(file);else if(item.isFile())files.push(file);else throw new Error(`Unexpected non-regular file: ${file}`);}}
await walk(stage);files.sort();
const checksums=[];
for(const file of files){const digest=createHash('sha256').update(await readFile(file)).digest('hex');checksums.push(`${digest}  ${path.relative(stage,file).split(path.sep).join('/')}`);}
await writeFile(path.join(destination,'OVERLAY_SHA256SUMS'),checksums.join('\n')+'\n');
execFileSync('tar',['-czf',path.join(destination,'steam-overlay.tar.gz'),'-C',stage,'steam']);
console.log(`Prepared AI Dazi /steam overlay: ${files.length} verified files, source ${revision}`);
